name: Publish Slack Release Testing Status
description: 'Publish the release testing status to Slack channels based on a Google Document.'

inputs:
  platform:
    description: 'The platform for which the release testing status is being published (e.g., mobile, extension).'
    required: true
  google-document-id:
    description: 'The ID of the Google Document containing the release testing status.'
    required: true
  test-only:
    description: 'If set to true, the action will only run in test mode and not publish to production Slack channels.'
    required: false
    default: 'false'
  slack-api-key:
    description: 'The API key for Slack to post the release testing status.'
    required: true
  github-token:
    description: 'The GitHub token for authentication.'
    required: true
  google-application-creds-base64:
    description: 'Base64 encoded Google application credentials for accessing Google Docs.'
    required: true
  github-tools-repository:
    description: 'The GitHub repository containing the GitHub tools. Defaults to the GitHub tools action repositor, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_repository }}
  github-tools-ref:
    description: 'The SHA of the action to use. Defaults to the current action ref, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_ref }}

runs:
  using: composite
  steps:
    - name: Checkout GitHub tools repository
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.github-tools-repository }}
        ref: ${{ inputs.github-tools-ref }}
        path: ./github-tools

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ./github-tools/.nvmrc
        cache-dependency-path: ./github-tools/yarn.lock
        cache: yarn

    - name: Enable Corepack
      run: corepack enable
      shell: bash
      working-directory: ./github-tools

    - name: Install dependencies
      run: yarn --immutable
      shell: bash
      working-directory: ./github-tools

    - name: Publish Slack Release Testing Status
      id: publish-slack-release-testing-status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SLACK_API_KEY: ${{ inputs.slack-api-key }}
        GOOG_DOCUMENT_ID: ${{ inputs.google-document-id }}
        GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ inputs.google-application-creds-base64 }}
        TEST_ONLY: ${{ inputs.test-only }}
        PLATFORM: ${{ inputs.platform }}
      working-directory: ./github-tools
      run: |
        yarn run slack:release-testing
