name: 'Close stale issues and PRs'
description: 'Automatically mark issues and pull requests as stale after a period of inactivity, and close them after an additional period of inactivity.'

inputs:
  stale-issue-message:
    description: 'Message to post when marking an issue as stale'
    required: false
    default: 'This issue has been automatically marked as stale because it has not had recent activity in the last 30 days. It will be closed in 60 days. Thank you for your contributions.'
  close-issue-message:
    description: 'Message to post when closing a stale issue'
    required: false
    default: 'This issue was closed because there has been no follow activity in 90 days. If you feel this was closed in error please provide evidence on the current production app in a new issue or comment in the existing issue to a maintainer. Thank you for your contributions.'
  stale-issue-label:
    description: 'Label to use when marking an issue as stale'
    required: false
    default: 'stale'
  any-of-issue-labels:
    description: 'Comma-separated list of labels to check for issues'
    required: false
    default: 'needs-information, needs-reproduction'
  exempt-issue-labels:
    description: 'Comma-separated list of labels that exempt issues from being marked as stale'
    required: false
    default: 'type-security, feature-request, Sev1-high, needs-triage'
  days-before-issue-stale:
    description: 'Number of days of inactivity before an issue becomes stale'
    required: false
    default: 30
  days-before-issue-close:
    description: 'Number of days of inactivity before a stale issue is closed'
    required: false
    default: 60
  stale-pr-message:
    description: 'Message to post when marking a PR as stale'
    required: false
    default: 'This PR has been automatically marked as stale because it has not had recent activity in the last 90 days. It will be closed in 7 days. Thank you for your contributions.'
  stale-pr-label:
    description: 'Label to use when marking a PR as stale'
    required: false
    default: 'stale'
  exempt-pr-labels:
    description: 'Comma-separated list of labels that exempt PRs from being marked as stale'
    required: false
    default: 'work-in-progress, external-contributor'
  close-pr-message:
    description: 'Message to post when closing a stale PR'
    required: false
    default: 'This PR was closed because there has been no follow up activity in 7 days. Thank you for your contributions.'
  days-before-pr-stale:
    description: 'Number of days of inactivity before a PR becomes stale'
    required: false
    default: '90'
  days-before-pr-close:
    description: 'Number of days of inactivity before a stale PR is closed'
    required: false
    default: '7'
  operations-per-run:
    description: 'Maximum number of operations to perform per run'
    required: false
    default: '200'

runs:
  using: composite
  steps:
    - uses: actions/stale@v10
      with:
        stale-issue-message: ${{ inputs.stale-issue-message }}
        close-issue-message: ${{ inputs.close-issue-message }}
        stale-issue-label: ${{ inputs.stale-issue-label }}
        any-of-issue-labels: ${{ inputs.any-of-issue-labels }}
        exempt-issue-labels: ${{ inputs.exempt-issue-labels }}
        days-before-issue-stale: ${{ inputs.days-before-issue-stale }}
        days-before-issue-close: ${{ inputs.days-before-issue-close }}
        stale-pr-message: ${{ inputs.stale-pr-message }}
        stale-pr-label: ${{ inputs.stale-pr-label }}
        exempt-pr-labels: ${{ inputs.exempt-pr-labels }}
        close-pr-message: ${{ inputs.close-pr-message }}
        days-before-pr-stale: ${{ inputs.days-before-pr-stale }}
        days-before-pr-close: ${{ inputs.days-before-pr-close }}
        operations-per-run: ${{ inputs.operations-per-run }}
