name: Upload S3

description: Upload S3

inputs:
  aws-region:
    required: true
    type: string
  role-to-assume:
    required: true
    type: string
  s3-bucket:
    required: true
    type: string
  path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}

    - name: Upload to S3
      env:
        UPLOAD_PATH: ${{ inputs.path }}
        S3_BUCKET: ${{ inputs.s3-bucket }}

      run: |
        if [ -d "$UPLOAD_PATH" ]; then
          aws s3 cp "$UPLOAD_PATH" "s3://$S3_BUCKET" --recursive
        else
          aws s3 cp "$UPLOAD_PATH" "s3://$S3_BUCKET"
        fi
      shell: bash
