name: Update Release Changelog
description: 'Update the release changelog for a given release branch.'

inputs:
  release-branch:
    required: true
    description: 'Release branch name (e.g., Version-v13.3.0 or release/6.20.0).'
  platform:
    required: false
    default: 'extension'
    description: 'Target platform (extension | mobile). Defaults to extension.'
  repository-url:
    required: true
    description: 'Full HTTPS URL for the invoking repository.'
  previous-version-ref:
    required: false
    default: 'null'
    description: 'Previous release version reference (branch/tag/SHA). Use "null" for hotfixes.'
  github-token:
    required: true
    description: 'GitHub token with write access to the invoking repository and read access to planning resources.'
  github-tools-repository:
    description: 'The GitHub repository containing the GitHub tools. Defaults to the GitHub tools action repositor, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_repository }}
  github-tools-ref:
    description: 'The SHA of the action to use. Defaults to the current action ref, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_ref }}

runs:
  using: composite
  steps:
    # Step 1: Checkout invoking repository (metamask-mobile | metamask-extension)
    - name: Checkout invoking repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ inputs.release-branch }}
        token: ${{ inputs.github-token }}

    # Step 2: Checkout github-tools repository
    - name: Checkout GitHub tools repository
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.github-tools-repository }}
        ref: ${{ inputs.github-tools-ref }}
        path: ./github-tools

    # Step 3: Setup environment from github-tools
    - name: Checkout and setup environment
      uses: ./github-tools/.github/actions/checkout-and-setup
      with:
        is-high-risk-environment: true

    # Step 4: Update changelog using shared helper script
    - name: Update changelog branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GIT_AUTHOR_NAME: metamaskbot
        GIT_AUTHOR_EMAIL: metamaskbot@users.noreply.github.com
        RELEASE_BRANCH: ${{ inputs.release-branch }}
        PLATFORM: ${{ inputs.platform }}
        REPOSITORY_URL: ${{ inputs.repository-url }}
        PREVIOUS_VERSION_REF: ${{ inputs.previous-version-ref }}
      run: |
        set -euo pipefail

        corepack enable
        yarn install --immutable

        ./github-tools/.github/scripts/update-release-changelog.sh \
          "$RELEASE_BRANCH" \
          "$PLATFORM" \
          "$REPOSITORY_URL" \
          "$PREVIOUS_VERSION_REF"
