name: Checkout and setup environment
inputs:
  should-cache-restore:
    required: false
    default: 'false'
  should-cache-save:
    required: false
    default: 'false'
  fetch-depth:
    required: false
    default: 1
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Only checkout code if the working folder is empty (no README.md), do not overwrite an existing custom checkout
      if: ${{ hashFiles('README.md') == '' }}
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - run: corepack enable
      shell: bash

    - name: Download workspace
      id: downloadWorkspace
      uses: actions/cache/restore@v4
      with:
        path: ./node_modules
        key: workspace-${{ github.sha }}

    # - run: echo ${{ toJSON(steps.downloadWorkspace.outputs) }}
    #   shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        # If we are not restoring from workspace cache, use setup-node cache to restore the '.yarn' folder
        # Notes: if this is always set to 'yarn':
        #   1) Self-hosted runners will fail to find this cache, and then fail on the 'Post Setup environment' step
        #   2) This action will run a few seconds slower, because when we restore the 'node_modules' folder from cache, there's no need to download the '.yarn' folder too
        # (GHA does not allow the : ? ternary operator, you must write && ||)
        cache: ${{ steps.downloadWorkspace.outputs.cache-hit != 'true' && 'yarn' || '' }}

    - name: Install dependencies
      if: ${{ steps.downloadWorkspace.outputs.cache-hit != 'true'}}
      run: yarn --immutable
      shell: bash

    - name: Cache workspace
      if: ${{ inputs.should-cache-save == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ./node_modules
        key: workspace-${{ github.sha }}
