name: Flaky Test Report
description: 'Generates a report of flaky tests from a specified GitHub Actions workflow and sends it to a Slack channel.'

inputs:
  repository:
    description: 'Repository name (e.g. metamask-extension)'
    required: true
  workflow-id:
    description: 'Workflow ID to analyze (e.g. main.yml)'
    required: true
  github-token:
    description: 'GitHub token with repo and actions:read access'
    required: true
  slack-webhook-flaky-tests:
    description: 'Slack webhook URL for flaky test reports'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout github-tools repository
      uses: actions/checkout@v4
      with:
        repository: MetaMask/github-tools
        path: github-tools

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./github-tools/.nvmrc
        cache-dependency-path: ./github-tools/yarn.lock
        cache: yarn

    - name: Enable Corepack
      working-directory: ./github-tools
      shell: bash
      run: corepack enable

    - name: Install dependencies
      working-directory: ./github-tools
      shell: bash
      run: yarn --immutable

    - name: Run flaky test report script
      env:
        REPOSITORY: ${{ inputs.repository }}
        WORKFLOW_ID: ${{ inputs.workflow-id }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SLACK_WEBHOOK_FLAKY_TESTS: ${{ inputs.slack-webhook-flaky-tests }}
      working-directory: ./github-tools
      shell: bash
      run: node .github/scripts/create-flaky-test-report.mjs
