name: 'Setup E2E Test Environment'
description: 'Sets up the environment for running E2E tests'
inputs:
  platform:
    description: 'Platform (ios or android)'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20.18.0'
  yarn-version:
    description: Yarn version to use with Corepack
    required: false
    default: '1.22.22'
  setup-simulator:
    description: 'Whether to setup simulator/emulator'
    required: false
    default: 'false'
  # See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
  ios-simulator-device: 
    description: Name of iOS simulator device to boot (e.g., "iPhone 15")
    required: false
    default: "iPhone 15"
  bundler-version:
    description: 'Bundler version to use (only for iOS)'
    required: false
    default: '2.5.8'
  cache-prefix:
    description: 'Cache key prefix'
    required: false
    default: 'e2e'
  ruby-version:
    description: Ruby version to use (only for iOS)
    required: false
    default: "3.1"
  xcode-version:
    description: Xcode version to select (e.g., 16.0)
    required: false
    default: "15.0"
  jdk-version:
    description: JDK version to use (only for Android)
    required: false
    default: "17"
  jdk-distribution:
    description: JDK distribution to use (only for Android)
    required: false
    default: "temurin"
  ndk-version:
    description: NDK version to use (only for Android)
    required: false
    default: "26.1.10909125"
  foundry-version:
    description: Foundry version to install
    required: false
    default: "v1.2.3"



runs:
  using: "composite"
  steps:

## Common Setup ##
    - run: echo "Setup E2E Environment started"
      shell: bash

## Yarn Setup & Cache Management

    - name: Corepack
      id: corepack
      run: corepack enable && corepack prepare yarn@${{ inputs.yarn-version }} --activate
      shell: bash


    - name: Restore Yarn cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ inputs.cache-prefix }}-yarn-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-yarn-${{ inputs.platform }}-${{ runner.os }}-

    - name: Install JavaScript dependencies
      id: yarn-install
      if: ${{ inputs.platform == 'ios' }}
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Detox CLI
      id: install-detox-cli
      run: yarn global add detox-cli
      shell: bash

    - name: Install Foundry
      shell: bash
      run: |
        echo "Installing Foundry via foundryup..."
        
        export FOUNDRY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/.foundry"
        export FOUNDRY_BIN="$FOUNDRY_DIR/bin"

        mkdir -p "$FOUNDRY_BIN"

        curl -sL https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup -o "$FOUNDRY_BIN/foundryup"
        chmod +x "$FOUNDRY_BIN/foundryup"

        echo "$FOUNDRY_BIN" >> "$GITHUB_PATH"

        "$FOUNDRY_BIN/foundryup"




## IOS Setup ##

## Ruby Setup & Cache Management
    - name: Setup Ruby
      if: ${{ inputs.platform == 'ios' }}
      uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651
      with:
        ruby-version: ${{ inputs.ruby-version }}

    # Install Bundler first
    - name: Install bundler
      if: ${{ inputs.platform == 'ios' }}
      run: gem install bundler -v ${{ inputs.bundler-version }}
      shell: bash

    # Restore cached Ruby gems
    - name: Restore Bundler cache
      if: ${{ inputs.platform == 'ios' }}
      uses: actions/cache@v4
      with:
        path: ios/vendor/bundle
        key: ${{ inputs.cache-prefix }}-bundler-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('ios/Gemfile.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-bundler-${{ inputs.platform }}-${{ runner.os }}-

    # Configure bundler to use a specific path for gem installation
    - name: Configure bundler install path
      if: ${{ inputs.platform == 'ios' }}
      run: bundle config set path 'vendor/bundle'
      working-directory: ios
      shell: bash

    # Install Ruby gems into ios/vendor/bundle ( cache management & awareness )
    - name: Install Ruby gems via bundler
      if: ${{ inputs.platform == 'ios' }}
      run: bundle install
      working-directory: ios
      shell: bash

    - name: Select Xcode version
      if: ${{ inputs.platform == 'ios' }}
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app
      shell: bash

    - name: Restore CocoaPods cache
      if: ${{ inputs.platform == 'ios' && inputs.setup-simulator == 'true' }}
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ inputs.cache-prefix }}-pods-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-pods-${{ inputs.platform }}-${{ runner.os }}-


    - name: Install CocoaPods via bundler
      if: ${{ inputs.platform == 'ios' && inputs.setup-simulator == 'true' }}
      run: bundle exec pod install
      working-directory: ios
      shell: bash

    - name: Install applesimutils
      if: ${{ inputs.platform == 'ios' }}
      run: brew tap wix/brew && brew install applesimutils
      shell: bash

    - name: Boot iOS Simulator (if not already booted)
      if: ${{ inputs.platform == 'ios' && inputs.setup-simulator == 'true' }}
      run: |
        echo "Looking for simulator named: ${{ inputs.ios-simulator-device }}"

        SIMULATOR_LINE=$(xcrun simctl list devices | grep -m1 "${{ inputs.ios-simulator-device }}")
        if [ -z "$SIMULATOR_LINE" ]; then
          echo "No simulator found with name '${{ inputs.ios-simulator-device }}'"
          exit 1
        fi

        SIMULATOR_ID=$(echo "$SIMULATOR_LINE" | awk -F '[()]' '{print $2}')
        SIMULATOR_STATE=$(echo "$SIMULATOR_LINE" | awk -F '[()]' '{print $(NF-1)}')

        echo "Simulator ID: $SIMULATOR_ID"
        echo "Simulator State: $SIMULATOR_STATE"

        if [ "$SIMULATOR_STATE" = "Booted" ]; then
          echo "Simulator is already booted. Skipping boot step."
        else
          echo "Booting simulator..."
          xcrun simctl boot "$SIMULATOR_ID"
        fi
      shell: bash

## Android Setup

## JDK Setup
    - name: Setup Java
      if: ${{ inputs.platform == 'android' }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: ${{ inputs.jdk-distribution }}

## Android SDK Setup

    - name: Install required emulator dependencies
      if: ${{ inputs.platform == 'android' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse0 libglu1-mesa
      shell: bash

    - name: Install Android SDK packages
      if: ${{ inputs.platform == 'android' }}
      run: |
        echo "Accepting SDK licenses..."
        printf 'y\n%.0s' {1..10} | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses

        echo "Installing Android SDK components..."
        "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "emulator" \
          "system-images;android-34;google_apis;x86_64"

        echo "Updating SDK packages..."
        "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --update
      shell: bash


 ## NDK Setup

    - name: Debug Android SDK Paths
      if: ${{ inputs.platform == 'android' }}
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
      shell: bash


    - name: Accept Android SDK licenses
      if: ${{ inputs.platform == 'android' }}
      run: |
        echo "Accepting Android SDK licenses..."
        bash -c 'yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses' || true
      shell: bash


    - name: Install Android SDK Packages
      if: ${{ inputs.platform == 'android' }}
      run: |
        "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "emulator" \
          "system-images;android-34;google_apis;x86_64"
      shell: bash

    - name: Install Android NDK
      if: ${{ inputs.platform == 'android' }}
      run: |
        "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "ndk;${{ inputs.ndk-version }}"
      shell: bash

    - name: Add Android tools to PATH
      if: ${{ inputs.platform == 'android' }}
      run: |
        echo "$ANDROID_HOME/platform-tools" >> "$GITHUB_PATH"
        echo "$ANDROID_HOME/emulator" >> "$GITHUB_PATH"
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Add NDK related toolchains to PATH
      if: ${{ inputs.platform == 'android' }}
      run: |
          NDK_TOOLCHAIN="$ANDROID_SDK_ROOT/ndk/${{ inputs.ndk-version }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "$NDK_TOOLCHAIN" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/ndk/${{ inputs.ndk-version }}" >> "$GITHUB_PATH"
      shell : bash

    - name: Check Installed NDK Versions
      run: |
        echo "Installed NDKs:"
        ls -la "$ANDROID_SDK_ROOT/ndk" || echo "No NDK installed"
      shell: bash
