name: 'Setup E2E Test Environment'
description: 'Sets up the environment for running E2E tests'
inputs:
  platform:
    description: 'Platform (ios or android)'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20.18.0'
  yarn-version:
    description: Yarn version to use with Corepack
    required: false
    default: '1.22.22'
  setup-simulator:
    description: 'Whether to setup simulator/emulator'
    required: false
    default: 'false'
  # See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
  ios-simulator-device: 
    description: Name of iOS simulator device to boot (e.g., "iPhone 15")
    required: false
    default: "iPhone 15"
  bundler-version:
    description: 'Bundler version to use (only for iOS)'
    required: false
    default: '2.5.8'
  cache-prefix:
    description: 'Cache key prefix'
    required: false
    default: 'e2e'
  ruby-version:
    description: Ruby version to use (only for iOS)
    required: false
    default: "3.1"
  xcode-version:
    description: Xcode version to select (e.g., 16.0)
    required: false
    default: "15.0"


runs:
  using: "composite"
  steps:

## Common Setup ##
    - run: echo "Setup E2E Environment started"
      shell: bash

## Yarn Setup & Cache Management

    - name: Install Yarn
      run: corepack enable && corepack prepare yarn@${{ inputs.yarn-version }} --activate
      shell: bash


    - name: Restore Yarn cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ inputs.cache-prefix }}-yarn-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-yarn-${{ inputs.platform }}-${{ runner.os }}-

    - name: Install JavaScript dependencies
      if: ${{ inputs.platform == 'ios' }}
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Detox CLI
      run: yarn global add detox-cli
      shell: bash

    - name: Install Foundry
      run: curl -L https://foundry.paradigm.xyz | bash && ~/.foundry/bin/foundryup
      shell: bash

## IOS Setup ##

## Ruby Setup & Cache Management
    - name: Setup Ruby
      if: ${{ inputs.platform == 'ios' }}
      uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651
      with:
        ruby-version: ${{ inputs.ruby-version }}

    # Install Bundler first
    - name: Install bundler
      if: ${{ inputs.platform == 'ios' }}
      run: gem install bundler -v ${{ inputs.bundler-version }}
      shell: bash

    # Restore cached Ruby gems
    - name: Restore Bundler cache
      if: ${{ inputs.platform == 'ios' }}
      uses: actions/cache@v4
      with:
        path: ios/vendor/bundle
        key: ${{ inputs.cache-prefix }}-bundler-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('ios/Gemfile.lock') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-bundler-${{ inputs.platform }}-${{ runner.os }}-

    # Install Ruby gems into ios/vendor/bundle ( cache management & awareness )
    - name: Install Ruby gems via bundler
      if: ${{ inputs.platform == 'ios' }}
      run: bundle install --path=vendor/bundle
      working-directory: ios
      shell: bash

    - name: Select Xcode version
      if: ${{ inputs.platform == 'ios' }}
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app
      shell: bash

    - name: Install CocoaPods via bundler
      if: ${{ inputs.platform == 'ios' && inputs.setup-simulator == 'true' }}
      run: bundle exec pod install
      working-directory: ios
      shell: bash

    - name: Install applesimutils
      if: ${{ inputs.platform == 'ios' }}
      run: brew tap wix/brew && brew install applesimutils
      shell: bash

    - name: Boot iOS Simulator (if not already booted)
      if: ${{ inputs.platform == 'ios' && inputs.setup-simulator == 'true' }}
      run: |
        echo "Looking for simulator named: ${{ inputs.ios-simulator-device }}"

        SIMULATOR_LINE=$(xcrun simctl list devices | grep -m1 "${{ inputs.ios-simulator-device }}")
        if [ -z "$SIMULATOR_LINE" ]; then
          echo "No simulator found with name '${{ inputs.ios-simulator-device }}'"
          exit 1
        fi

        SIMULATOR_ID=$(echo "$SIMULATOR_LINE" | awk -F '[()]' '{print $2}')
        SIMULATOR_STATE=$(echo "$SIMULATOR_LINE" | awk -F '[()]' '{print $(NF-1)}')

        echo "Simulator ID: $SIMULATOR_ID"
        echo "Simulator State: $SIMULATOR_STATE"

        if [ "$SIMULATOR_STATE" = "Booted" ]; then
          echo "Simulator is already booted. Skipping boot step."
        else
          echo "Booting simulator..."
          xcrun simctl boot "$SIMULATOR_ID"
        fi
      shell: bash

## Android Setup
    - name: Setup Java
      if: ${{ inputs.platform == 'android' }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00





    



    
