name: Add team label

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  add-team-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get team label
        id: get-team-label
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USER: ${{ github.event.pull_request.user.login }}
        run: |
          team_label=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/metamask/metamask-planning/contents/teams.json' --jq .$USER)
          if [ -z "$team_label" ]; then
            echo "::error file=teams.json::Team label not found for author: $USER. Please open a pull request with your GitHub handle and team label to update teams.json at https://github.com/MetaMask/MetaMask-planning/blob/main/teams.json"
            exit 1
          fi
          echo 'TEAM_LABEL='$team_label >> $GITHUB_OUTPUT

      - name: Add team label
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER: ${{ github.event.repository.owner }}
          REPOSITORY: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          TEAM_LABEL: ${{ steps.get-team-label.outputs.TEAM_LABEL }}
        run: |
          gh api -X POST -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' repos/$OWNER/$REPOSITORY/issues/$PULL_REQUEST_NUMBER/labels -f "labels[]=team-extension-platform"
