name: Add team label

on:
  workflow_call:
    secrets:
      TEAM_LABEL_TOKEN:
        required: true

jobs:
  add-team-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get team label
        id: get-team-label
        env:
          GH_TOKEN: ${{ secrets.TEAM_LABEL_TOKEN }}
          USER: ${{ github.event.pull_request.user.login }}
        run: |
          team_label=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/metamask/metamask-planning/contents/teams.json' --jq ".\"$USER\"")
          if [ -z "$team_label" ]; then
            echo "::error::Team label not found for author: $USER. Please open a pull request with your GitHub handle and team label to update teams.json at https://github.com/MetaMask/MetaMask-planning/blob/main/teams.json"
            exit 1
          fi
          echo 'TEAM_LABEL='"$team_label" >> "$GITHUB_OUTPUT"

      - name: Add team label
        env:
          GH_TOKEN: ${{ secrets.TEAM_LABEL_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          TEAM_LABEL: ${{ steps.get-team-label.outputs.TEAM_LABEL }}
        run: |
          gh api --method POST --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/issues/$PR_NUMBER/labels -f "labels[]=$TEAM_LABEL"
