name: Add team label test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  add-team-label:
    uses: ./.github/workflows/add-team-label.yml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.LABEL_TOKEN }}
