name: Add team label test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  add-team-label:
    permissions: read-all
    uses: ./.github/workflows/add-team-label.yml
