name: Add team label

on:
  workflow_call:

jobs:
  add-team-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get teams
        id: teams
        uses: octokit/graphql-action@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query teams($organization:String!,$user:String!) {
              organization(login: $organization) {
                teams(first: 100, userLogins: [$user]) {
                  edges {
                    node {
                      name
                      description
                      slug
                    }
                  }
                }
              }
            }
          variables: |
            organization: ${{ github.event.repository.owner.name }}
            user: ${{ github.event.pull_request.user.login }}

      - run: "echo '${{ steps.teams.outputs.data }}'"
