name: Add team label

on:
  workflow_call:

jobs:
  add-team-label:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Get teams
        id: teams
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          USER: ${{ github.event.pull_request.user.login }}
        run: |
          teams="$(gh api graphql -F organization=$ORGANIZATION -F user=$USER -f query='
            query($organization: String!, $user: String!) {
              organization(login: $organization) {
                teams(first: 100, userLogins: [$user]) {
                  edges {
                    node {
                      name
                      description
                      slug
                    }
                  }
                }
              }
            }
          ' --jq '.')"
          echo 'TEAMS='$teams >> $GITHUB_ENV

      - run: 'echo $TEAMS'
