name: Add team label

on:
  pull_request:
    types:
      - opened

jobs:
  add-team-label:
    uses: ./.github/workflows/add-team-label.yml
    permissions:
      pull-requests: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.LABEL_TOKEN }}
