name: Add team label

on:
  workflow_call:

jobs:
  add-team-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get team label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.event.pull_request.user.login }}
        run: |
          team_label="$(gh api -H 'Accept: application/vnd.github.raw' 'repos/metamask/metamask-planning/contents/teams.json' --jq '.$USER')"
          echo 'TEAM_LABEL='$team_label >> $GITHUB_ENV

      - run: 'echo $TEAM_LABEL'
