name: Get release timelines

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'The version of the release'

jobs:
  get-release-timelines:
    uses: ./.github/workflows/get-release-timelines.yml
    with:
      version: 12.13.0
    secrets:
      RUNWAY_APP_ID: ''
      RUNWAY_API_KEY: ''
