name: Get release timelines

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'The version of the release'

jobs:
  get-release-timelines:
    uses: ./.github/workflows/get-release-timelines.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      RUNWAY_APP_ID: ''
      RUNWAY_API_KEY: ''
