name: Lint workflows

on:
  workflow_call:

jobs:
  lint-workflows:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash)
        shell: bash

      - name: Lint workflow files
        env:
          EXECUTABLE: ${{ steps.download-actionlint.outputs.executable }}
        run: |
          "$EXECUTABLE" -color
        shell: bash
