name: Lint workflows

on:
  workflow_call:

jobs:
  lint-workflows:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/011a6d15e749bb3f2d771eed9c7aa0e7e3e10ee7/scripts/download-actionlint.bash) 1.7.12
        shell: bash

      - name: Lint workflow files
        env:
          EXECUTABLE: ${{ steps.download-actionlint.outputs.executable }}
        run: |
          "$EXECUTABLE" -color
        shell: bash
