name: Log number of daily merged PRs

on:
  schedule:
    # Run daily at midnight UTC to get the previous day's data
    - cron: '0 0 * * *'
  workflow_call:
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
      GOOGLE_SERVICE_ACCOUNT:
        required: true
      SPREADSHEET_ID:
        required: true
      SHEET_NAME:
        required: true
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  log-daily-pr-merges:
    name: Log number of daily merged PRs
    runs-on: ubuntu-latest
    steps:
      - name: Download oauth2l
        run: |
          curl --silent https://storage.googleapis.com/oauth2l/1.3.2/linux_amd64.tgz | tar xz
          echo "$PWD/linux_amd64" >> "$GITHUB_PATH"

      - name: Create service_account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT" > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Get yesterday's date
        id: yesterday
        run: |
          # Get yesterday's date in YYYY-MM-DD format
          YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)
          echo "yesterday=$YESTERDAY" >> $GITHUB_OUTPUT
          echo "Yesterday's date: $YESTERDAY"

      - name: Count PRs merged yesterday
        id: count_prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the repository name from GITHUB_REPOSITORY
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          echo "Repository: $REPO_NAME"
          
          # Count PRs merged yesterday into main branch
          # Using GitHub API to search for PRs merged on yesterday's date
          YESTERDAY="${{ steps.yesterday.outputs.yesterday }}"
          
          # Search for PRs merged yesterday
          PR_COUNT=$(curl --silent \
            --header "Authorization: token $GITHUB_TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/issues?q=repo:$GITHUB_REPOSITORY+is:pr+is:merged+merged:$YESTERDAY..$YESTERDAY+base:main" \
            | jq '.total_count')
          
          echo "PRs merged yesterday: $PR_COUNT"
          echo "pr_count=$PR_COUNT" >> $GITHUB_OUTPUT

      - name: Write data to google sheets
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: |
          YESTERDAY="${{ steps.yesterday.outputs.yesterday }}"
          PR_COUNT="${{ steps.count_prs.outputs.pr_count }}"
          
          # Get OAuth token
          token=$(oauth2l fetch --scope https://www.googleapis.com/auth/spreadsheets)
          
          # Read existing data to check if yesterday's row exists
          spreadsheet_data=$(curl --silent --header "Authorization: Bearer $token" \
            https://sheets.googleapis.com/v4/spreadsheets/"$SPREADSHEET_ID"/values/"$SHEET_NAME"!A:C)
          
          # Check if yesterday's date exists in column A
          current_date_index=$(echo "$spreadsheet_data" | jq --arg yesterday "$YESTERDAY" \
            '(.values | map(.[0])) | (index($yesterday) | if . == null then null else . + 1 end)')
          
          if [ "$current_date_index" == "null" ]; then
            # Date doesn't exist, append new row with PR count in column C
            curl --silent --header "Authorization: Bearer $token" \
              --header "Content-Type: application/json" \
              --request POST \
              --data "{\"values\":[[\"$YESTERDAY\", \"\", $PR_COUNT]]}" \
              https://sheets.googleapis.com/v4/spreadsheets/"$SPREADSHEET_ID"/values/"$SHEET_NAME"!A:C:append?valueInputOption=USER_ENTERED
            echo "Added new row for $YESTERDAY with $PR_COUNT PRs merged"
          else
            # Date exists, update column C with PR count
            curl --silent --header "Authorization: Bearer $token" \
              --header "Content-Type: application/json" \
              --request PUT \
              --data "{\"values\":[[$PR_COUNT]]}" \
              https://sheets.googleapis.com/v4/spreadsheets/"$SPREADSHEET_ID"/values/"$SHEET_NAME"!C"$current_date_index":C"$current_date_index"?valueInputOption=USER_ENTERED
            echo "Updated row $current_date_index for $YESTERDAY with $PR_COUNT PRs merged"
          fi 