name: Post RCA Form

permissions:
  issues: write
  contents: read

on:
  workflow_call:
    inputs:
      google-form-base-url:
        description: Base URL of the Google Form.
        required: true
        type: string
      repo-owner:
        description: The repo owner
        required: true
        type: string
      repo-name:
        description: The repo name
        required: true
        type: string
      issue-number:
        description: The number of the closed issue
        required: true
        type: string
      issue-labels:
        description: JSON-stringified array of labels that should trigger the RCA prompt
        required: true
        type: string
      entry-issue:
        description: The entry ID for the issue field in the Google Form
        required: true
        type: string
      entry-regression:
        description: The entry ID for the regression field in the Google Form
        required: true
        type: string
      entry-team:
        description: The entry ID for the team field in the Google Form
        required: true
        type: string

jobs:
  post-rca-form:
    name: Post Google Form link and log results on issue close
    runs-on: ubuntu-latest
    steps:
      - name: Post RCA Form Link
        uses: actions/github-script@v7
        env:
          GOOGLE_FORM_BASE_URL: ${{ inputs.google-form-base-url }}
          ISSUE_LABELS:        ${{ inputs.issue-labels }}
          OWNER_NAME:          ${{ inputs.repo-owner }}
          REPO_NAME:           ${{ inputs.repo-name }}
          ISSUE_NUMBER:        ${{ inputs.issue-number }}
          ENTRY_ISSUE:         ${{ inputs.entry-issue }}
          ENTRY_REGRESSION:    ${{ inputs.entry-regression }}
          ENTRY_TEAM:          ${{ inputs.entry-team }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {
              GOOGLE_FORM_BASE_URL: baseUrl,
              ENTRY_ISSUE,
              ENTRY_REGRESSION,
              ENTRY_TEAM,
              OWNER_NAME: owner,
              REPO_NAME: repo,
              ISSUE_NUMBER: issueNumStr,
            } = process.env;

            const issue_number  = parseInt(issueNumStr, 10);
            const allowedLabels = JSON.parse(process.env.ISSUE_LABELS);

            // Fetch issue details to get the assignees
            const { data: issue } = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issue_number,
            });

            const hasAllowedLabel = issue.labels.some(label =>
              allowedLabels.includes(label.name)
            );

            if (!hasAllowedLabel) {
              console.log(`❌ Issue #${issue_number} skipped — no matching label.`);
              return;
            }

            // if it's a sev1-high or sev0-high, lets grab team and regression labels, if there's any
            // if there's none, an empty value will be sent, which is what we want
            const teamLabels = issue.labels
              .map(l => l.name)
              .filter(n => n.startsWith('team-'));

            const regressionLabels = issue.labels
              .map(l => l.name)
              .filter(n => n.startsWith('regression-'));

            const formUrl = new URL(baseUrl);
            formUrl.searchParams.set(ENTRY_ISSUE, issue_number);
            formUrl.searchParams.set(
              ENTRY_REGRESSION,
              regressionLabels.length ? regressionLabels.join(',') : ''
            );
            formUrl.searchParams.set(
              ENTRY_TEAM,
              teamLabels.length ? teamLabels.join(',') : ''
            );

            const assignees = issue.assignees.map(u=>`@${u.login}`).join(', ');
            const body = `Hi ${assignees},

            This issue has been closed. Please complete this RCA form:
            ${formUrl.toString()}

            <!-- AUTO-FORM -->`;

            await github.rest.issues.createComment({
              owner, repo, issue_number, body
            });
            console.log(`✅ Comment posted on issue #${issue_number}`);
