name: Publish Slack Release Testing Status

on:
  workflow_call:
    inputs:
      platform: # possible values are [ mobile, extension ]
        required: true
        type: string
      google-document-id:
        required: true
        type: string
        default: '1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ'
      # Controls whether to actually publish to production slack channels, true will publish to prod slack channels
      test-only:
        required: false
        type: string
        default: 'false'
    secrets:
      slack-api-key:
        required: true
      github-token:
        required: true
      google-application-creds-base64:
        required: true

jobs:
  publish-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Step 2: Checkout github-tools repository
      - name: Checkout github-tools repository
        uses: actions/checkout@v4
        with:
          repository: MetaMask/github-tools
          ref: slack-release-testing #TODO Update to main
          path: github-tools

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./github-tools/.nvmrc
          cache-dependency-path: ./github-tools/yarn.lock
          cache: yarn

      - name: Enable Corepack
        run: corepack enable
        shell: bash
        working-directory: ./github-tools

      - name: Install dependencies
        run: yarn --immutable
        shell: bash
        working-directory: ./github-tools

      # Step 4: Run Script
      - name: Publish Slack Release Testing Status
        id: publish-slack-release-testing-status
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          SLACK_API_KEY: ${{ secrets.slack-api-key }}
          GOOG_DOCUMENT_ID: ${{ inputs.google-document-id }}
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.google-application-creds-base64 }}
          TEST_ONLY: ${{inputs.test-only}}
        working-directory: ./github-tools
        run: |
          yarn run slack:release-testing
