name: Publish Slack Release Testing Status

on:
  workflow_call:
    inputs:
      platform: # possible values are [ mobile, extension ]
        required: true
        type: string
      google-document-id:
        required: true
        type: string
        default: '1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ'
    secrets:
      slack-api-key:
        required: true
      github-token:
        required: true
      google-credentials-creds-base64:
        required: true

jobs:
  publish-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Step 1: Checkout invoking repository (metamask-mobile | metamask-extension )
      - name: Checkout invoking repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      # Step 2: Checkout github-tools repository
      - name: Checkout github-tools repository
        uses: actions/checkout@v4
        with:
          repository: MetaMask/github-tools
          ref: slack-release-testing #TODO Update to main
          path: github-tools

      # Step 3: Setup environment from github-tools
      - name: Setup environment
        uses: ./github-tools/.github/actions/setup-environment

      # Step 4: Run Script
      - name: Publish Slack Release Testing Status
        id: publish-slack-release-testing-status
        shell: bash
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
          SLACK_API_KEY: ${{ inputs.slack-api-key }}
          GOOG_DOCUMENT_ID: ${{ inputs.google-document-id }}
          GOOGLE_CREDENTIALS_CREDS_BASE64: ${{ inputs.google-credentials-creds-base64 }}
          TEST_ONLY: 'true' #TODO Remove this line
        working-directory: ./github-tools
        run: |
          yarn run slack:release-testing
