name: Test Merge Validationn

on:
  push:
    branches:
      - chore-post-validation

permissions:
  pull-requests: write
  contents: read

jobs:
  test-validation:
    uses: ./.github/workflows/post-merge-validation.yml
    with:
      repo-owner: ${{ github.repository_owner }}
      repo-name: ${{ github.event.repository.name }}
      pr-number: ${{ github.event.pull_request.number }}
      pr-author: ${{ github.event.pull_request.user.login }}
      pr-title: ${{ github.event.pull_request.title }}
