name: Test "Add Team Label" Action

on:
  workflow_call:
    secrets:
      TEAM_LABEL_TOKEN:
        required: true

jobs:
  add-team-label:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Test
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/add-team-label
        with:
          team-label-token: ${{ secrets.TEAM_LABEL_TOKEN }}
