name: Get Release Timelines
description: 'Get release timelines from Runway and upload as artifact.'

inputs:
  version:
    required: true
    description: The version of the release.
  github-token:
    required: true
    description: The GitHub token used for authentication.
  runway-app-id:
    required: true
    description: The Runway application ID.
  runway-api-key:
    required: true
    description: The Runway API key.
  github-tools-repository:
    description: 'The GitHub repository containing the GitHub tools. Defaults to the GitHub tools action repositor, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_repository }}
  github-tools-ref:
    description: 'The SHA of the action to use. Defaults to the current action ref, and usually does not need to be changed.'
    required: false
    default: ${{ github.action_ref }}

runs:
  using: composite
  steps:
    - name: Checkout GitHub tools repository
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.github-tools-repository }}
        ref: ${{ inputs.github-tools-ref }}
        path: ./github-tools

    - name: Get release timelines
      env:
        OWNER: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.event.repository.name }}
        VERSION: ${{ inputs.version }}
        RUNWAY_APP_ID: ${{ inputs.runway-app-id }}
        RUNWAY_API_KEY: ${{ inputs.runway-api-key }}
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: ./github-tools/.github/scripts/get-release-timelines.sh

    - name: Upload artifact release-timelines-${{ inputs.version }}.csv
      uses: actions/upload-artifact@v4
      with:
        name: release-timelines-${{ inputs.version }}.csv
        path: release-timelines-${{ inputs.version }}.csv
